FROM mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
#------------------------------------------------------------------------------
WORKDIR /app
COPY ./app /app
ENTRYPOINT /app/entrypoint.sh
#------------------------------------------------------------------------------
